"""Rename description to intent in features_table

Revision ID: f10d58bd7143
Revises: 4d8eaf70b6b3
Create Date: 2024-12-08 11:19:22.115782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10d58bd7143'
down_revision = '4d8eaf70b6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features_table', schema=None) as batch_op:
        batch_op.drop_column('intent')

    # ### end Alembic commands ###
